---
- name: apdb
  hosts: ap31
  become: true
  become_method: sudo
  tasks:
  - name: creation nouvelle db sdis2022
    community.mysql.mysql_db:
      name: sdis29
      login_user: root
      login_password: admin
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: creation utilisateur ap31 
    community.mysql.mysql_user:
      login_user: root
      login_password: admin
      name: Slam
      password: Slam1+
      priv: 'sdis29.*:ALL'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
